name: Runner Info

on:
  push:

jobs:

  info:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Current Directory
        run: pwd

      - name: Show Files
        run: ls -la

      - name: Show OS
        run: cat /etc/os-release

      - name: Show User
        run: whoami

      - name: Show Docker Version
        run: docker --version
